/* Bot settings 

You don't have to set this if you deploy using heroku because you can simply set them in environment variables, also don't forget to sleep */


const session = process.env.SESSION || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQ0Fub0ZidE9TVTc3aTlrdnFqTEtoRkJocFJNblB4VGovM1oxMHlpNjZIdz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoicTBCM0ozOUxBQjU3RmdwRVpyYk5hVFpyRG1pK2w0TWhtNWtVeUZhNVZqVT0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJhTHRsL0s1ZHNUVXRzdW1qbG5SS1FmcHZRdnJ6OXJFR1dHbFl5UndRUFhBPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiIzR0RSeml1WUY5UzhXTXBxVDNjMVpIeWExZHN3a1daQld0aEhNZEJXU2hRPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjhGNUVoS0VYTTcyajUrdDlVd1d0eXB5NHVSRTE0dk5UaXNYSGwxeUFRMTA9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ik05MGRvTmt4SUNUZ3RoSDI5RUE2NFA2WlVTVzZ4c2FQb3hHOGpiNk5zQVE9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoid0FhZiswYmQyVVlqMGI5cnJFNm4zYUxBWC93S3kzdXMrbStIMjdKMnhWRT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiNDFVTU1QcDNUR1c1dFBSMUg2dTBmUnlLWmU4RmdMT25hMGNCUDVDMVZVTT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ik9RU2xhdG5zNHIrR2FOZTNDZmhYUDRLSS9MVXNEcEd3NlhvbUJEbnZlVUVzdU8yN25DcEIyZkN6SDBRVngvUXFRa295eEExR0RROHBKcWM5NlIwbmhBPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MjAzLCJhZHZTZWNyZXRLZXkiOiJ6NnlKTEwvTlI4TlJFa2FlVTNXN2w3ZTNKb3JiWXNwbWwrSEZJVDM2WmxvPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W10sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjowLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwiZGV2aWNlSWQiOiJyTk5EclJGNlI1SzJib0kwT3Flanh3IiwicGhvbmVJZCI6IjNhODc4MThlLTUwZTMtNDgzMi04NzRmLWZlMDg1ZTYwNDY2NCIsImlkZW50aXR5SWQiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJIV2FTaFJhZkFtSlZGVXFRa3ltRUM0dTdZWjQ9In0sInJlZ2lzdGVyZWQiOnRydWUsImJhY2t1cFRva2VuIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiL3NaUjBSbXR2MTByckZxbmR3Lys2MTJSUUZvPSJ9LCJyZWdpc3RyYXRpb24iOnt9LCJwYWlyaW5nQ29kZSI6IlQ2R0RWVkFOIiwibWUiOnsiaWQiOiI5MjMyMjUyOTQ2MDU6NjdAcy53aGF0c2FwcC5uZXQifSwiYWNjb3VudCI6eyJkZXRhaWxzIjoiQ0kvLzR2RUZFUFdYejdrR0dBTWdBQ2dBIiwiYWNjb3VudFNpZ25hdHVyZUtleSI6IlY5VGdWd1V2bkhtV1V1MmZSVEljeUlDaW56c1JUNC90OCtSODZONVRVVFE9IiwiYWNjb3VudFNpZ25hdHVyZSI6IkpldXJ0RzNlc0lZMGE2Z2kyaFZ0enNEdEgrdkpxK0plbmRiT3hoRllLK2phbm41VDlKSlViVlVvcmxudzhuNVZab2Z4OVQ2cllHVlUwZmZ1aWVGb0J3PT0iLCJkZXZpY2VTaWduYXR1cmUiOiJzSHBBcWNBVFM5OHVIK1g4eEdQTVZXN29CQ0FlRGFqOG0xUXRQbVpiSmdYanNVWGdsOFJJTFI1RWZnWGRwV0kyTVpIUGg1V1lGQlpzUGsxS1VtTUZoQT09In0sInNpZ25hbElkZW50aXRpZXMiOlt7ImlkZW50aWZpZXIiOnsibmFtZSI6IjkyMzIyNTI5NDYwNTo2N0BzLndoYXRzYXBwLm5ldCIsImRldmljZUlkIjowfSwiaWRlbnRpZmllcktleSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkJWZlU0RmNGTDV4NWxsTHRuMFV5SE1pQW9wODdFVStQN2ZQa2ZPamVVMUUwIn19XSwicGxhdGZvcm0iOiJhbmRyb2lkIiwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzMxNDQ3ODEwLCJteUFwcFN0YXRlS2V5SWQiOiJBQUFBQU1nZiJ9';

const prefix = process.env.PREFIX || '.';
const mycode = process.env.CODE || "254";
const author = process.env.STICKER_AUTHOR || 'Keith';
const packname = process.env.PACKNAME || 'keith';
const dev = process.env.DEV || '254748387615';
const DevDreaded = dev.split(",");
const botname = process.env.BOTNAME || 'KEITH-MD';
const mode = process.env.MODE || 'public';
const gcpresence = process.env.GC_PRESENCE || 'false';
const antionce = process.env.ANTIVIEWONCE || 'true';
const sessionName = "session";
const presence = process.env.WA_PRESENCE || 'online';

const antitag = process.env.ANTITAG || 'true';
const antidelete = process.env.ANTIDELETE || 'true';
const autoview = process.env.AUTOVIEW_STATUS || 'true';
const autolike = process.env.AUTOLIKE_STATUS || 'true';
const autoread = process.env.AUTOREAD || 'true';
const autobio = process.env.AUTOBIO || 'false';

module.exports = {
  sessionName,
  presence,
  autoview,
  autoread,
  botname,
  autobio,
  mode,
  prefix,
  autolike,
  mycode,
  author,
  packname,
  dev,
  DevDreaded,
  gcpresence,
  antionce,
session,
antitag,
antidelete
};
