/* Bot settings 

You don't have to set this if you deploy using heroku because you can simply set them in environment variables, also don't forget to sleep */


const session = process.env.SESSION || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiWUFaTjhwa0tUenFzS21CeDhjZnJNYm1sSFFoVkh3TmNmUHhKTWp1ejdIdz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoicnY5Y0RKM2ZjRUZ5d2N6U0R2b3dVbGs0TjJjQjRKb1RsWGV2L0JUT1NBaz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJFRWk2NzNSanZORHk4Z2RxeW02Rk1GVGZDbTN6STZqNzBNZmZIR0R3bDFJPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJmU1JZamtPMzhHbUxPR1RQeWRhOUpURnRHOW1vZlUvUldpRWt4elFsV1hFPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InVOYmVwbEtlSlZXeGJBdE5XMVZkSHNBbmovbHA0TXVMQlNoR2Uyb0RJbGM9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkgrU282OGpXWjRsV2x5R21NOGl4SzZHYXFvRHcxcG5MQnRpYjZtenFobHM9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiTUJoclg3b1VxVWpzNm5DOWxHOGxGai9jRDR6WHJSaEVUOXlCYXBVenBtZz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoibEVQQnhQTjQrRHhaZDI2OXBQT1pHdEdoR3hsMzFwb2FrbDM4VE9rU2dSUT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImtKL1VZVTNCMGsxczk2VEJ3bzFiUzNGYmdsdW9LUFZGanpLRWFNU1EvKzExOWNhNnJvMlpXSGZlZlhwTHZUdFpuYWZTWUhXQVBQMHlhUEhTUDk0WUJBPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6NzMsImFkdlNlY3JldEtleSI6IkdVZjVaZ0lQeVlaU2UxajJxYnIvK1ZiSVlDbjJyNk9NWWp3VkdyTCt6R0U9IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbXSwibmV4dFByZUtleUlkIjozMSwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWQiOjMxLCJhY2NvdW50U3luY0NvdW50ZXIiOjAsImFjY291bnRTZXR0aW5ncyI6eyJ1bmFyY2hpdmVDaGF0cyI6ZmFsc2V9LCJkZXZpY2VJZCI6ImpPNm9PQ1dQVFktcXZaa21GeEI2V0EiLCJwaG9uZUlkIjoiYTI1MzQwNmMtYzIzNS00ZTM2LWFlMzItMTBkY2Q4ZTUxYWNkIiwiaWRlbnRpdHlJZCI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ijc4dCtWL1A5TVdMaVA3azVlSUpDRHlOTGhITT0ifSwicmVnaXN0ZXJlZCI6dHJ1ZSwiYmFja3VwVG9rZW4iOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJkWGhsd1pXTndzajVVRjFaL3ZRSUowSkcrNmM9In0sInJlZ2lzdHJhdGlvbiI6e30sInBhaXJpbmdDb2RlIjoiWDExUTg0VkIiLCJtZSI6eyJpZCI6IjkyMzIyNTI5NDYwNTo3OUBzLndoYXRzYXBwLm5ldCJ9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDSmIvNHZFRkVNR2EzYmtHR0FFZ0FDZ0EiLCJhY2NvdW50U2lnbmF0dXJlS2V5IjoiVjlUZ1Z3VXZuSG1XVXUyZlJUSWN5SUNpbnpzUlQ0L3Q4K1I4Nk41VFVUUT0iLCJhY2NvdW50U2lnbmF0dXJlIjoicWd4aE90YklnYnFhRkl2R2tiODRNandKUkRYSkUxYXB1Qi9oQXdDN1E1UkxJYTl5dnBteUhxOWNwM3lSMS8yQzkzVFpseDZKWVNyaXlVZ0NBb1VVRGc9PSIsImRldmljZVNpZ25hdHVyZSI6IlM2NmgvczVyVkdKdXpNRzhDdmxjUnR5VWNOQmJaUjVyaWs5Y0dQbjBQQU9jNTcvQmprdXJ2a2J5SzROY1dBZENXZ0l2Vkh4Rzh1aE95TnV0UnNjcERBPT0ifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiOTIzMjI1Mjk0NjA1Ojc5QHMud2hhdHNhcHAubmV0IiwiZGV2aWNlSWQiOjB9LCJpZGVudGlmaWVyS2V5Ijp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQlZmVTRGY0ZMNXg1bGxMdG4wVXlITWlBb3A4N0VVK1A3ZlBrZk9qZVUxRTAifX1dLCJwbGF0Zm9ybSI6ImFuZHJvaWQiLCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXAiOjE3MzE2Nzc1MTgsIm15QXBwU3RhdGVLZXlJZCI6IkFBQUFBTWdnIn0=';

const prefix = process.env.PREFIX || '.';
const mycode = process.env.CODE || "254";
const author = process.env.STICKER_AUTHOR || 'Keith';
const packname = process.env.PACKNAME || 'keith';
const dev = process.env.DEV || '254748387615';
const DevDreaded = dev.split(",");
const botname = process.env.BOTNAME || 'KEITH-MD';
const mode = process.env.MODE || 'public';
const gcpresence = process.env.GC_PRESENCE || 'false';
const antionce = process.env.ANTIVIEWONCE || 'true';
const sessionName = "session";
const presence = process.env.WA_PRESENCE || 'online';

const antitag = process.env.ANTITAG || 'true';
const antidelete = process.env.ANTIDELETE || 'true';
const autoview = process.env.AUTOVIEW_STATUS || 'true';
const autolike = process.env.AUTOLIKE_STATUS || 'true';
const autoread = process.env.AUTOREAD || 'true';
const autobio = process.env.AUTOBIO || 'false';

module.exports = {
  sessionName,
  presence,
  autoview,
  autoread,
  botname,
  autobio,
  mode,
  prefix,
  autolike,
  mycode,
  author,
  packname,
  dev,
  DevDreaded,
  gcpresence,
  antionce,
session,
antitag,
antidelete
};
