/* Bot settings 

You don't have to set this if you deploy using heroku because you can simply set them in environment variables, also don't forget to sleep */


const session = process.env.SESSION || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiS1B6SWlzSEpTdGU2b2RLT0JjaG1MNkhScGg2R2tsZThRaGpyZ2VIZG1Faz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoicDhrQkV2Q3oxUG4yTXdmd2lvbW1CRDFvTXZoYVBBazNGSUJ4anl4a0lqbz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJ1S2JKRUNsbjA5Y1Vkc1g5Z3ZsL0ErSkk5d3pJVStGVVVPalNkVHpDQm1JPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJ0OHlsd3RoMFIvd0l3TjlxazduQXNnc0JHanhibmFHVnFGa2syZHlaUVRrPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlNDMXNuSHk4cVhZMGpaQUtHZGRnbW1CcmtDUnJUbkJyU1FmWUE5WElxbWs9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkZZSXMrdUpjMXVlSXd4d1JnQm5ETGVnZ3lNc0lKZ3JOS2tjNXlaWkFXM0E9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiWUUxVDJ1eERYYUxGY3JKc2d3b09vNXJwTEg1SjFqOFdQK2VNUTU1dDNYaz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiRlNoTXYwc1dNcGpiU3RtSzMwcUh6QnJhSVROQWR0cDRVY1EvMHBJT2xuMD0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjFnc3IwdDdMZjN1aVdZRk8rcXNlcFRBNG9kTEQzbUluZDV2YXFsNE5pVmM3QnJuR2QrK0FrU3NBTUhkcmdIL0R6RjlZREdybW5pK3pOOXo0TUJuN0NnPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTI3LCJhZHZTZWNyZXRLZXkiOiJLeFA5azNwc3NXTEFVNFMyc0ZJTGFzK0QzVkJFZ0JwekdGVVd4RWZySU5RPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W10sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjowLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwiZGV2aWNlSWQiOiJ6aUtJNjE2Q1MzZUszcERQdTlUdDN3IiwicGhvbmVJZCI6ImI5MWQ1MGVkLTJkZTktNDFjZC1iZmI1LWI2NTY5MzBhODNjMyIsImlkZW50aXR5SWQiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiIwUkg5eE5kV1VOUlNrS05pSFBDVkU3ZzRoUjQ9In0sInJlZ2lzdGVyZWQiOnRydWUsImJhY2t1cFRva2VuIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiRUdRbUllOUdURklaZXBNOFI0NTczR2VIUGVvPSJ9LCJyZWdpc3RyYXRpb24iOnt9LCJwYWlyaW5nQ29kZSI6IjI1UU1RU0xEIiwibWUiOnsiaWQiOiI5NzE1NjE3Mzg2MzU6NUBzLndoYXRzYXBwLm5ldCJ9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDSlQxNUtjRUVOK3QyTGtHR0FJZ0FDZ0EiLCJhY2NvdW50U2lnbmF0dXJlS2V5Ijoia2gvMjlPdGwvWDBuNGl0SjUwNFcxdG91SVltYTJYMHdiKzVNMmROSG5TYz0iLCJhY2NvdW50U2lnbmF0dXJlIjoiMS95WC9TMTNMRm56amIwSHA1Q05ObjZtZE9lWExGOGd5NEVPMjZtSGJUbzNrVSszMzErQ2dkZlpyYXFJU3JaNVFxWCtoWmRuZEdMYmt2aVl5YlRIREE9PSIsImRldmljZVNpZ25hdHVyZSI6Iit3UmRDWk9QY21pcEhWcmI5MENXY25zZTFHdGJSdTV5WEx3WEN5MEp6WTZ4alplKytpQng3L2hUYkJMU3dXbzVsSmxOV1M3dENVRU5LMnpVZzFnakRRPT0ifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiOTcxNTYxNzM4NjM1OjVAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCWklmOXZUclpmMTlKK0lyU2VkT0Z0YmFMaUdKbXRsOU1HL3VUTm5UUjUwbiJ9fV0sInBsYXRmb3JtIjoiYW5kcm9pZCIsImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcCI6MTczMTU5ODA2MCwibXlBcHBTdGF0ZUtleUlkIjoiQUFBQUFKU00ifQ==';

const prefix = process.env.PREFIX || '.';
const mycode = process.env.CODE || "254";
const author = process.env.STICKER_AUTHOR || 'Keith';
const packname = process.env.PACKNAME || 'keith';
const dev = process.env.DEV || '254748387615';
const DevDreaded = dev.split(",");
const botname = process.env.BOTNAME || 'KEITH-MD';
const mode = process.env.MODE || 'public';
const gcpresence = process.env.GC_PRESENCE || 'false';
const antionce = process.env.ANTIVIEWONCE || 'true';
const sessionName = "session";
const presence = process.env.WA_PRESENCE || 'online';

const antitag = process.env.ANTITAG || 'true';
const antidelete = process.env.ANTIDELETE || 'true';
const autoview = process.env.AUTOVIEW_STATUS || 'true';
const autolike = process.env.AUTOLIKE_STATUS || 'true';
const autoread = process.env.AUTOREAD || 'true';
const autobio = process.env.AUTOBIO || 'false';

module.exports = {
  sessionName,
  presence,
  autoview,
  autoread,
  botname,
  autobio,
  mode,
  prefix,
  autolike,
  mycode,
  author,
  packname,
  dev,
  DevDreaded,
  gcpresence,
  antionce,
session,
antitag,
antidelete
};
